// ─── Goodreads Import Reset ───────────────────────────────────────────────────
//
// Scope: clear the Goodreads-imported layer for a user, preserving any row
// that has meaningful native in-app activity.
//
// This is NOT a general "delete my data" function. It only touches rows that
// have import_source = 'goodreads'. Recommendations, friendships, profile
// state, yearly goal, and activity generated by native app actions are
// preserved throughout.
//
// Native-touch heuristics (any one triggers preservation):
//   1. current_page IS NOT NULL — user recorded reading progress in-app
//      (Goodreads CSV does not export current page; this is always native)
//   2. Has activity_events rows referencing this user_book
//   3. Book is referenced in a recommendation involving this user
//      (from_user_id = userId OR to_user_id = userId)
//
// Preserved rows: import provenance fields are cleared so the row is eligible
// for a clean merge on the next Goodreads reimport, without losing native state.
//
// Purely-imported rows: deleted entirely (no cascade risk — the heuristics
// above guarantee no activity_events or recommendation references remain).
//
// Import staging tables: import_batches for this user are deleted.
// import_rows cascade-delete automatically via FK ON DELETE CASCADE.
//
// book_source_links: intentionally NOT deleted — they are shared catalog data
// that improves matching quality on a future reimport.

import { supabase } from './supabase';

export type GoodreadsResetResult = {
  preserved: number;
  removed: number;
};

function chunk<T>(arr: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < arr.length; i += size) out.push(arr.slice(i, i + size));
  return out;
}

export async function resetGoodreadsImport(userId: string): Promise<GoodreadsResetResult> {
  if (!supabase) throw new Error('Supabase not available');

  // ── 1. Fetch all Goodreads-imported user_books ────────────────────────────
  const { data: imported, error: fetchErr } = await supabase
    .from('user_books')
    .select('id, book_id, current_page')
    .eq('user_id', userId)
    .eq('import_source', 'goodreads');

  if (fetchErr) throw fetchErr;
  if (!imported || imported.length === 0) {
    await cleanupImportBatches(userId);
    return { preserved: 0, removed: 0 };
  }

  const allIds    = imported.map(r => r.id as string);
  const allBookIds = imported.map(r => r.book_id as string);

  // ── 2. Native-touch signal: current_page ─────────────────────────────────
  const progressTouched = new Set(
    imported.filter(r => r.current_page != null).map(r => r.id as string),
  );

  // ── 3. Native-touch signal: activity_events ───────────────────────────────
  const activityTouched = new Set<string>();
  for (const ids of chunk(allIds, 100)) {
    const { data } = await supabase
      .from('activity_events')
      .select('user_book_id')
      .in('user_book_id', ids);
    for (const r of data ?? []) {
      if (r.user_book_id) activityTouched.add(r.user_book_id as string);
    }
  }

  // ── 4. Native-touch signal: recommendations ───────────────────────────────
  const recTouchedBookIds = new Set<string>();
  for (const bookIds of chunk(allBookIds, 100)) {
    const { data } = await supabase
      .from('recommendations')
      .select('book_id')
      .in('book_id', bookIds)
      .or(`from_user_id.eq.${userId},to_user_id.eq.${userId}`);
    for (const r of data ?? []) {
      if (r.book_id) recTouchedBookIds.add(r.book_id as string);
    }
  }

  const recTouched = new Set(
    imported
      .filter(r => recTouchedBookIds.has(r.book_id as string))
      .map(r => r.id as string),
  );

  // ── 5. Partition ──────────────────────────────────────────────────────────
  const nativeTouchedIds: string[]   = [];
  const purelyImportedIds: string[]  = [];

  for (const row of imported) {
    const id = row.id as string;
    if (progressTouched.has(id) || activityTouched.has(id) || recTouched.has(id)) {
      nativeTouchedIds.push(id);
    } else {
      purelyImportedIds.push(id);
    }
  }

  // ── 6. Clear provenance on native-touched rows ────────────────────────────
  // Clearing these fields makes the row eligible for a clean merge on reimport
  // while keeping all native state (status, rating, review, progress, etc.).
  for (const ids of chunk(nativeTouchedIds, 100)) {
    const { error } = await supabase
      .from('user_books')
      .update({
        import_source:          null,
        import_source_book_id:  null,
        import_batch_id:        null,
        imported_at:            null,
      })
      .in('id', ids);
    if (error) throw error;
  }

  // ── 7. Delete purely-imported rows ────────────────────────────────────────
  for (const ids of chunk(purelyImportedIds, 100)) {
    const { error } = await supabase
      .from('user_books')
      .delete()
      .in('id', ids);
    if (error) throw error;
  }

  // ── 8. Delete import_batches (import_rows cascade via FK) ─────────────────
  await cleanupImportBatches(userId);

  return {
    preserved: nativeTouchedIds.length,
    removed:   purelyImportedIds.length,
  };
}

async function cleanupImportBatches(userId: string): Promise<void> {
  if (!supabase) return;
  await supabase
    .from('import_batches')
    .delete()
    .eq('user_id', userId)
    .eq('source', 'goodreads');
}
